on: push
name: CI/CD
jobs:
  FTP-Deploy-Action:
    name: CI&CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Build Packages
        run: pnpm run build
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


